version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_SCHEMA
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/scripts/db:/tmp/db
    command: mysqld --init-file="/tmp/db/install_db.sql"
  auth-service:
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - $PORT:$DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_SCHEMA
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
volumes: 
  db_data: