version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_SCHEMA
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./scripts/db:/tmp/db
    command: mysqld --init-file="/tmp/db/install_db.sql"
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_SCHEMA
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db: